import { Router, type IRouter } from "express";
import { ListCaseStudiesResponse } from "@workspace/api-zod";

const router: IRouter = Router();

router.get("/case-studies", async (_req, res): Promise<void> => {
  const caseStudies = [
    {
      id: 1,
      title: "Educate Girls Development Impact Bond",
      location: "Rajasthan (Bhilwara, Ajmer, Tonk districts)",
      state: "Rajasthan",
      organization: "Educate Girls",
      organizationUrl: "https://www.educategirls.ngo",
      targetGroup: "Out-of-school girls aged 6-14 in rural areas",
      model: "Community mobilization via village volunteers (Team Balika); government school partnerships; data-driven enrollment targeting",
      costPerBeneficiary: "INR 1,200–1,800 per enrolled girl per year",
      outcomes: "166% of enrollment target met; 116% of learning outcome target met; investors received full principal + return. Enrolled 18,000+ girls over 3 years.",
      yearsActive: "2015–2018",
      fundingSource: "UBS Optimus Foundation (investor), CIFF (outcome funder), DFID",
      fundingLinks: [
        { name: "UBS Optimus Foundation", url: "https://www.ubs.com/microsites/optimus-foundation/en/home.html" },
        { name: "Children's Investment Fund Foundation (CIFF)", url: "https://ciff.org" },
        { name: "British Asian Trust (DIB Facilitator)", url: "https://www.britishasiantrust.org" },
      ],
    },
    {
      id: 2,
      title: "Pratham TaRL Remedial Learning Program",
      location: "Bihar, Uttar Pradesh, Maharashtra, Rajasthan",
      state: "Multiple States",
      organization: "Pratham",
      organizationUrl: "https://www.pratham.org",
      targetGroup: "Children in grades 3-5 with below-grade literacy and numeracy",
      model: "Children regrouped by skill level (not grade); taught basic reading/arithmetic via play activities; 45-day intensive camps run by trained community volunteers",
      costPerBeneficiary: "INR 800–1,500 per child for a 45-day camp",
      outcomes: "J-PAL RCT: doubled proportion of grade-3 children reading at grade level. Learning gains of 0.4-0.7 SD in literacy and numeracy.",
      yearsActive: "2005–present",
      fundingSource: "Skoll Foundation, private donors, state government partnerships",
      fundingLinks: [
        { name: "Skoll Foundation", url: "https://skoll.org" },
        { name: "J-PAL South Asia (Research Partner)", url: "https://www.povertyactionlab.org/south-asia" },
        { name: "TaRL Africa (Global Expansion)", url: "https://www.teachingattherightlevel.org" },
      ],
    },
    {
      id: 3,
      title: "Akanksha Foundation Urban School Centers",
      location: "Mumbai and Pune",
      state: "Maharashtra",
      organization: "Akanksha Foundation",
      organizationUrl: "https://www.akanksha.org",
      targetGroup: "Children from urban slums aged 6-18",
      model: "After-school centers and full-day centers within municipal school buildings; mentorship, life skills, parental engagement, psychosocial support; partnership with BMC and PMC",
      costPerBeneficiary: "INR 40,000–55,000 per student per year",
      outcomes: "90% of students complete SSC vs 60% municipal average; 85% enroll in higher education or vocational training. 15,000+ students impacted.",
      yearsActive: "1991–present",
      fundingSource: "CSR (HDFC Bank, Axis Bank), individual donors, government grants",
      fundingLinks: [
        { name: "HDFC Bank CSR", url: "https://www.hdfcbank.com/content/bbp/repositories/723fb80a-2dde-42a3-9793-7ae1be57c87f/?folderName=/OurCSRActivities" },
        { name: "Axis Bank Foundation", url: "https://www.axisbankfoundation.org" },
        { name: "Brihanmumbai Municipal Corporation (BMC)", url: "https://portal.mcgm.gov.in" },
      ],
    },
    {
      id: 4,
      title: "eVidyaloka Satellite-Connected Rural Tutoring",
      location: "Pan-India (22 states)",
      state: "Multiple States",
      organization: "eVidyaloka",
      organizationUrl: "https://www.evidyaloka.org",
      targetGroup: "Class 5-10 students in remote government schools lacking qualified subject teachers",
      model: "Urban volunteer teachers deliver live online classes to rural classrooms via affordable video setup; covers Math, Science, English, Social Studies",
      costPerBeneficiary: "INR 3,000–5,000 per student per year",
      outcomes: "35-40% improvement in subject scores over one academic year; active in 800+ schools; 35,000+ students served annually.",
      yearsActive: "2011–present",
      fundingSource: "Individual donors, corporate CSR, NASSCOM Foundation",
      fundingLinks: [
        { name: "NASSCOM Foundation", url: "https://www.nasscomfoundation.org" },
        { name: "GiveIndia (Donor Platform)", url: "https://www.giveindia.org" },
      ],
    },
    {
      id: 5,
      title: "BRAC India Non-Formal Education (Bihar)",
      location: "Bihar (Muzaffarpur, Sitamarhi, East Champaran districts)",
      state: "Bihar",
      organization: "BRAC India",
      organizationUrl: "https://www.brac.net/country/india",
      targetGroup: "Out-of-school children aged 8-14 from marginalized families",
      model: "Community-based NFE centers (1 teacher, 30 students); accelerated learning over 12 months; transition to government primary schools after program completion",
      costPerBeneficiary: "INR 4,500–6,000 per child per year",
      outcomes: "90% of program completers transitioned to regular government schools; literacy improvement of 0.6 SD; 50,000+ children served over program duration.",
      yearsActive: "2002–2014",
      fundingSource: "DFID, EU, individual donors",
      fundingLinks: [
        { name: "FCDO / DFID (UK Aid)", url: "https://www.gov.uk/government/organisations/foreign-commonwealth-development-office" },
        { name: "EU Delegation to India", url: "https://www.eeas.europa.eu/delegations/india_en" },
      ],
    },
    {
      id: 6,
      title: "Kaivalya Education Foundation (KEF)",
      location: "Maharashtra, Rajasthan, Gujarat",
      state: "Multiple States",
      organization: "Kaivalya Education Foundation",
      organizationUrl: "https://www.kaivalya.org",
      targetGroup: "Students in under-resourced government schools; school leaders and teachers",
      model: "School leadership development for government school principals; teacher professional development; governance strengthening through district-level capacity building",
      costPerBeneficiary: "INR 15,000–25,000 per school leader trained per year",
      outcomes: "Schools with KEF-trained leaders show 25% improvement in student learning outcomes. 200,000+ students impacted across 1,500+ schools.",
      yearsActive: "2008–present",
      fundingSource: "Citi Foundation, Tata Trusts, Michael & Susan Dell Foundation",
      fundingLinks: [
        { name: "Citi Foundation", url: "https://www.citigroup.com/global/foundation" },
        { name: "Tata Trusts", url: "https://www.tatatrusts.org" },
        { name: "Michael & Susan Dell Foundation", url: "https://www.msdf.org" },
      ],
    },
    {
      id: 7,
      title: "Gram Vikas MANTRA Program (Odisha)",
      location: "Odisha (tribal districts)",
      state: "Odisha",
      organization: "Gram Vikas",
      organizationUrl: "https://www.gramvikas.org",
      targetGroup: "Tribal children in remote Odisha; focus on SC/ST communities",
      model: "Integrated village development including community learning centers; parental literacy programs run alongside children's schooling; mother-tongue based multilingual education",
      costPerBeneficiary: "INR 2,500–4,000 per child per year",
      outcomes: "School enrollment increased 45% in target villages; learning outcomes in mother-tongue literacy improved 0.5 SD; 100,000+ community members across 1,000+ villages.",
      yearsActive: "1993–present",
      fundingSource: "DFID, EU, individual donors, government",
      fundingLinks: [
        { name: "FCDO / DFID (UK Aid)", url: "https://www.gov.uk/government/organisations/foreign-commonwealth-development-office" },
        { name: "EU Delegation to India", url: "https://www.eeas.europa.eu/delegations/india_en" },
        { name: "Odisha Government (DSME)", url: "https://schooleducation.odisha.gov.in" },
      ],
    },
    {
      id: 8,
      title: "Digital Empowerment Foundation IT Literacy (Bihar)",
      location: "Bihar (rural clusters)",
      state: "Bihar",
      organization: "Digital Empowerment Foundation",
      organizationUrl: "https://www.defindia.org",
      targetGroup: "Rural youth aged 15-25; focus on women and first-generation learners",
      model: "Community-based digital literacy centers with internet access; vocational digital skills training; content in local languages; mobile phone literacy integrated",
      costPerBeneficiary: "INR 2,000–3,500 per beneficiary",
      outcomes: "70% of trainees report using digital skills for economic activity within 6 months. 500,000+ people reached across Bihar and Jharkhand.",
      yearsActive: "2006–present",
      fundingSource: "USAID, GIZ, corporate CSR, individual donors",
      fundingLinks: [
        { name: "US Foreign Assistance to India", url: "https://foreignassistance.gov/cd/india/" },
        { name: "GIZ India (German Development)", url: "https://www.giz.de/en/worldwide/325.html" },
        { name: "NASSCOM Foundation", url: "https://www.nasscomfoundation.org" },
      ],
    },
    {
      id: 9,
      title: "Bachpan Bachao Andolan (Child Labour Rescue)",
      location: "Pan-India (UP, Bihar, Rajasthan priority zones)",
      state: "Multiple States",
      organization: "Bachpan Bachao Andolan",
      organizationUrl: "https://www.bba.org.in",
      targetGroup: "Child labourers aged 6-14; focus on bonded labour and factory work",
      model: "Investigation and rescue of child labourers; rehabilitation schools (Bal Ashrams); reintegration into mainstream education; legal advocacy and policy change",
      costPerBeneficiary: "INR 60,000–90,000 per rescued child (including rehabilitation)",
      outcomes: "80,000+ children rescued from labour and trafficking since 1980. 70%+ successfully reintegrated into mainstream schooling. Kailash Satyarthi awarded Nobel Peace Prize (2014).",
      yearsActive: "1980–present",
      fundingSource: "Individual donors, Ikea Foundation, Global March Against Child Labour",
      fundingLinks: [
        { name: "Kailash Satyarthi Children's Foundation", url: "https://satyarthi.org.in" },
        { name: "IKEA Foundation", url: "https://ikeafoundation.org" },
        { name: "Global March Against Child Labour", url: "https://www.globalmarch.org" },
      ],
    },
    {
      id: 10,
      title: "Azim Premji Foundation School Quality Improvement",
      location: "Karnataka, Uttarakhand, Rajasthan, Andhra Pradesh",
      state: "Multiple States",
      organization: "Azim Premji Foundation",
      organizationUrl: "https://azimpremjifoundation.org",
      targetGroup: "Government school students and teachers in underserved districts",
      model: "On-site teacher professional development; district-level resource centers; curriculum and pedagogical materials aligned with NCF; long-term 5-10 year partnerships with state governments",
      costPerBeneficiary: "INR 20,000–35,000 per teacher trained per year",
      outcomes: "Significant improvements in teacher quality and student learning in partner districts. 500+ district resource centers established; 150,000+ teachers reached annually.",
      yearsActive: "2001–present",
      fundingSource: "Azim Premji Foundation (philanthropic, $2B+ endowment)",
      fundingLinks: [
        { name: "Azim Premji University", url: "https://azimpremjiuniversity.edu.in" },
        { name: "Azim Premji Philanthropic Initiatives", url: "https://azimpremjifoundation.org/our-work" },
      ],
    },
  ];
  res.json(ListCaseStudiesResponse.parse(caseStudies));
});

export default router;
