import { Router, type IRouter } from "express";
import { ListExamsResponse } from "@workspace/api-zod";

const router: IRouter = Router();

const exams = [
  // ── ENGINEERING ──────────────────────────────────────────────
  {
    id: "jee-main",
    name: "Joint Entrance Examination Main",
    shortName: "JEE Main",
    category: "engineering" as const,
    level: "ug" as const,
    conductingBody: "National Testing Agency (NTA)",
    conductingBodyUrl: "https://nta.ac.in",
    officialWebsite: "https://jeemain.nta.ac.in",
    description: "Gateway exam for admission to NITs, IIITs, CFTIs, and other centrally funded technical institutions. Also a qualifier for JEE Advanced (IITs). Two sessions per year — Session 1 in January and Session 2 in April. Best of two scores is considered.",
    eligibility: "Class 12 pass/appearing with Physics, Chemistry, Maths. Max 2 attempts in consecutive years after Class 12.",
    applicationStart: "Nov 2025",
    applicationEnd: "Dec 2025",
    examDate: "Jan & Apr 2026",
    resultDate: "Feb & May 2026",
    totalSeats: 232000,
    candidatesAppearing: "12–14 lakh per session",
    mode: "online" as const,
    frequency: "biannual" as const,
    eligibleInstitutionTypes: ["nit", "iiit", "cfti"],
    acceptedBy: ["All 31 NITs", "All 25 IIITs", "All 3 SPAs", "IISTs", "IIEST Shibpur", "2000+ other institutes"],
  },
  {
    id: "jee-advanced",
    name: "Joint Entrance Examination Advanced",
    shortName: "JEE Advanced",
    category: "engineering" as const,
    level: "ug" as const,
    conductingBody: "IIT Kanpur (2026 organising IIT)",
    conductingBodyUrl: "https://jeeadv.ac.in",
    officialWebsite: "https://jeeadv.ac.in",
    description: "The most competitive engineering entrance in India. Only the top 2.5 lakh JEE Main qualifiers can apply. Admits students to all 23 IITs. Two papers of 3 hours each testing Physics, Chemistry, and Mathematics at the highest level.",
    eligibility: "Among top 2.5 lakh in JEE Main. Max 2 attempts. Born on or after Oct 1, 2001 (general). First attempt at Class 12 in 2025 or 2026.",
    applicationStart: "Apr 2026",
    applicationEnd: "Apr 2026",
    examDate: "May 2026",
    resultDate: "Jun 2026",
    totalSeats: 17385,
    candidatesAppearing: "~1.8 lakh appear",
    mode: "online" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["iit"],
    acceptedBy: ["All 23 IITs (17,385 seats)"],
  },
  {
    id: "gate",
    name: "Graduate Aptitude Test in Engineering",
    shortName: "GATE",
    category: "engineering" as const,
    level: "pg" as const,
    conductingBody: "IIT Roorkee (2026 organising IIT)",
    conductingBodyUrl: "https://gate2026.iitr.ac.in",
    officialWebsite: "https://gate2026.iitr.ac.in",
    description: "Nationwide PG engineering entrance for M.Tech/ME admissions at IITs, NITs, IISc, and IIITs. GATE score also used for PSU recruitment (ONGC, BHEL, DRDO, etc.) and fellowships. 30 subject papers covering all engineering and science disciplines.",
    eligibility: "B.Tech/BE/B.Arch/B.Sc Research or final year students. No age limit.",
    applicationStart: "Aug 2025",
    applicationEnd: "Sep 2025",
    examDate: "Feb 2026",
    resultDate: "Mar 2026",
    totalSeats: null,
    candidatesAppearing: "~10 lakh",
    mode: "online" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["iit", "nit", "cfti", "iiit"],
    acceptedBy: ["All 23 IITs", "All 31 NITs", "IISc", "All IIITs", "500+ institutes + PSU jobs"],
  },
  {
    id: "bitsat",
    name: "BITS Admission Test",
    shortName: "BITSAT",
    category: "engineering" as const,
    level: "ug" as const,
    conductingBody: "BITS Pilani",
    conductingBodyUrl: "https://www.bits-pilani.ac.in",
    officialWebsite: "https://www.bitsadmission.com",
    description: "Entrance to BITS Pilani's Integrated First Degree programmes across Pilani, Goa, and Hyderabad campuses. 130-question online test covering Physics, Chemistry, Maths, English, and Logical Reasoning.",
    eligibility: "Min 75% aggregate in PCM in Class 12. Born on or after Aug 1, 2005.",
    applicationStart: "Jan 2026",
    applicationEnd: "Mar 2026",
    examDate: "May–Jun 2026",
    resultDate: "Jun 2026",
    totalSeats: 2800,
    candidatesAppearing: "~3 lakh",
    mode: "online" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["cfti"],
    acceptedBy: ["BITS Pilani (Pilani, Goa, Hyderabad campuses)"],
  },

  // ── MEDICAL ──────────────────────────────────────────────────
  {
    id: "neet-ug",
    name: "National Eligibility cum Entrance Test Undergraduate",
    shortName: "NEET UG",
    category: "medical" as const,
    level: "ug" as const,
    conductingBody: "National Testing Agency (NTA)",
    conductingBodyUrl: "https://nta.ac.in",
    officialWebsite: "https://neet.nta.nic.in",
    description: "Single nationwide entrance for MBBS, BDS, BSc Nursing, BAMS, BHMS, and BVSc admissions in all government and private medical colleges. Mandatory for all 18 AIIMS, JIPMER Puducherry, and 704 medical colleges.",
    eligibility: "Class 12 with PCB minimum 50% (40% for SC/ST/OBC). Age 17–25 years. No attempt limit (Supreme Court ruling 2018).",
    applicationStart: "Feb 2026",
    applicationEnd: "Mar 2026",
    examDate: "May 2026",
    resultDate: "Jun 2026",
    totalSeats: 108940,
    candidatesAppearing: "~23–24 lakh",
    mode: "offline" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["aiims", "cfti", "state-university"],
    acceptedBy: ["All 18 AIIMS", "JIPMER Puducherry", "All 704 medical colleges across India"],
  },
  {
    id: "neet-pg",
    name: "National Eligibility cum Entrance Test Postgraduate",
    shortName: "NEET PG",
    category: "medical" as const,
    level: "pg" as const,
    conductingBody: "National Board of Examinations (NBE)",
    conductingBodyUrl: "https://natboard.edu.in",
    officialWebsite: "https://neetpg.natboard.edu.in",
    description: "Gateway for MD, MS, and Diploma admissions in all government and private medical colleges. Single merit list replaces all state-level PG entrance tests. Mandatory for all AIIMS PG programmes.",
    eligibility: "MBBS degree with compulsory rotating internship completed or expected to complete by March 31 of the admission year.",
    applicationStart: "Dec 2025",
    applicationEnd: "Jan 2026",
    examDate: "Mar 2026",
    resultDate: "Apr 2026",
    totalSeats: 53000,
    candidatesAppearing: "~2 lakh",
    mode: "online" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["aiims", "cfti", "central-university", "state-university"],
    acceptedBy: ["All AIIMS PG seats", "All government medical colleges", "Private medical colleges"],
  },
  {
    id: "aiims-pg",
    name: "AIIMS Postgraduate Entrance Examination",
    shortName: "AIIMS PG",
    category: "medical" as const,
    level: "pg" as const,
    conductingBody: "All India Institute of Medical Sciences Delhi",
    conductingBodyUrl: "https://www.aiims.edu",
    officialWebsite: "https://aiimsexams.ac.in",
    description: "Centralised PG entrance for all 18 AIIMS MD/MS/PhD seats. Conducted online twice yearly (January and July). Highly competitive with average 300–400 candidates per seat.",
    eligibility: "MBBS with at least 55% marks and completed internship.",
    applicationStart: "Oct 2025 / Apr 2026",
    applicationEnd: "Nov 2025 / May 2026",
    examDate: "Jan & Jul 2026",
    resultDate: "Feb & Aug 2026",
    totalSeats: 1500,
    candidatesAppearing: "~50,000 per session",
    mode: "online" as const,
    frequency: "biannual" as const,
    eligibleInstitutionTypes: ["aiims"],
    acceptedBy: ["All 18 AIIMS MD/MS/MDS seats"],
  },

  // ── MANAGEMENT ───────────────────────────────────────────────
  {
    id: "cat",
    name: "Common Admission Test",
    shortName: "CAT",
    category: "management" as const,
    level: "pg" as const,
    conductingBody: "Indian Institutes of Management (IIMs)",
    conductingBodyUrl: "https://www.iimcat.ac.in",
    officialWebsite: "https://iimcat.ac.in",
    description: "India's most prestigious MBA entrance. Conducted by one of the 21 IIMs on rotation. Tests Verbal Ability & Reading Comprehension, Data Interpretation & Logical Reasoning, and Quantitative Ability. Scores accepted by 1,200+ B-schools.",
    eligibility: "Bachelor's degree with minimum 50% marks (45% for SC/ST/PWD). Final year students can also apply.",
    applicationStart: "Aug 2025",
    applicationEnd: "Sep 2025",
    examDate: "Nov 2025",
    resultDate: "Jan 2026",
    totalSeats: 4500,
    candidatesAppearing: "~3 lakh",
    mode: "online" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["iim"],
    acceptedBy: ["All 21 IIMs", "FMS Delhi", "MDI Gurgaon", "SPJIMR", "1,200+ B-schools"],
  },
  {
    id: "xat",
    name: "Xavier Aptitude Test",
    shortName: "XAT",
    category: "management" as const,
    level: "pg" as const,
    conductingBody: "XLRI Jamshedpur",
    conductingBodyUrl: "https://xlri.ac.in",
    officialWebsite: "https://xatonline.in",
    description: "Second most accepted MBA entrance after CAT. Unique Decision Making section tests ethical and business judgement. Accepted by XLRI and 150+ institutes. GK paper additionally required for XLRI admission.",
    eligibility: "Bachelor's degree in any discipline. No minimum percentage. Final year students eligible.",
    applicationStart: "Aug 2025",
    applicationEnd: "Dec 2025",
    examDate: "Jan 2026",
    resultDate: "Jan 2026",
    totalSeats: null,
    candidatesAppearing: "~1 lakh",
    mode: "online" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["iim", "cfti"],
    acceptedBy: ["XLRI Jamshedpur", "TAPMI", "Great Lakes", "IMT Ghaziabad", "150+ institutes"],
  },
  {
    id: "cmat",
    name: "Common Management Admission Test",
    shortName: "CMAT",
    category: "management" as const,
    level: "pg" as const,
    conductingBody: "National Testing Agency (NTA)",
    conductingBodyUrl: "https://nta.ac.in",
    officialWebsite: "https://cmat.nta.nic.in",
    description: "NTA-conducted MBA entrance for AICTE-approved management institutes. More affordable and accessible pathway for students aiming at government-aided B-schools and NITs. Tests Quantitative Techniques, Logical Reasoning, Language Comprehension, and General Awareness.",
    eligibility: "Bachelor's degree with 50% marks. Final year students eligible. No age limit.",
    applicationStart: "Jan 2026",
    applicationEnd: "Feb 2026",
    examDate: "Mar 2026",
    resultDate: "Apr 2026",
    totalSeats: null,
    candidatesAppearing: "~75,000",
    mode: "online" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["nit", "cfti", "central-university", "state-university"],
    acceptedBy: ["All NITs offering MBA", "AICTE-approved B-schools", "Govt-aided institutes"],
  },

  // ── LAW ──────────────────────────────────────────────────────
  {
    id: "clat",
    name: "Common Law Admission Test",
    shortName: "CLAT",
    category: "law" as const,
    level: "ug" as const,
    conductingBody: "Consortium of National Law Universities",
    conductingBodyUrl: "https://consortiumofnlus.ac.in",
    officialWebsite: "https://consortiumofnlus.ac.in",
    description: "Single entrance for all 25 National Law Universities (NLUs). Comprehension-based exam testing English, Current Affairs & GK, Legal Reasoning, Logical Reasoning, and Quantitative Techniques. CLAT PG for LLM admissions is separate.",
    eligibility: "UG: Class 12 pass with 45% marks (40% for SC/ST). PG: LLB/BA LLB with 55% marks (50% SC/ST). No age limit.",
    applicationStart: "Jan 2026",
    applicationEnd: "Mar 2026",
    examDate: "May 2026",
    resultDate: "Jun 2026",
    totalSeats: 3500,
    candidatesAppearing: "~75,000",
    mode: "offline" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["nlaw"],
    acceptedBy: ["All 25 National Law Universities", "NALSAR Hyderabad", "NUJS Kolkata", "NLU Delhi (AILET separately)"],
  },
  {
    id: "ailet",
    name: "All India Law Entrance Test",
    shortName: "AILET",
    category: "law" as const,
    level: "ug" as const,
    conductingBody: "National Law University Delhi",
    conductingBodyUrl: "https://nludelhi.ac.in",
    officialWebsite: "https://nludelhi.ac.in/ailet",
    description: "Separate entrance for NLU Delhi only. NLU Delhi opted out of CLAT. Tests English, General Knowledge, Legal Aptitude, Reasoning, and Mathematics (Elementary). 110 seats for BA LLB and 70 seats for LLM.",
    eligibility: "Class 12 with 50% marks for UG. LLB with 55% for LLM. No age bar.",
    applicationStart: "Jan 2026",
    applicationEnd: "Mar 2026",
    examDate: "May 2026",
    resultDate: "May 2026",
    totalSeats: 110,
    candidatesAppearing: "~15,000",
    mode: "offline" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["nlaw"],
    acceptedBy: ["National Law University Delhi only"],
  },
  {
    id: "lsat-india",
    name: "Law School Admission Test — India",
    shortName: "LSAT India",
    category: "law" as const,
    level: "ug" as const,
    conductingBody: "Law School Admission Council (LSAC)",
    conductingBodyUrl: "https://www.lsac.org",
    officialWebsite: "https://lsat.pearsonvueindia.com",
    description: "International standard law school test adapted for India. Tests Analytical Reasoning, Logical Reasoning, and Reading Comprehension. Accepted by 60+ private law schools. Offers both UG (5-year integrated) and PG (LLM) pathways.",
    eligibility: "UG: Class 12 in any stream. PG: LLB/LLM degree. No specific percentage requirement.",
    applicationStart: "Oct 2025",
    applicationEnd: "Jan 2026",
    examDate: "Jan 2026",
    resultDate: "Feb 2026",
    totalSeats: null,
    candidatesAppearing: "~40,000",
    mode: "online" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["nlaw"],
    acceptedBy: ["Jindal Global Law School", "Symbiosis Law School", "60+ private law schools"],
  },

  // ── DESIGN ───────────────────────────────────────────────────
  {
    id: "uceed",
    name: "Undergraduate Common Entrance Examination for Design",
    shortName: "UCEED",
    category: "design" as const,
    level: "ug" as const,
    conductingBody: "IIT Bombay",
    conductingBodyUrl: "https://www.iitb.ac.in",
    officialWebsite: "https://uceed.iitb.ac.in",
    description: "Gateway to B.Des programmes at IITs and IISc. Tests visualisation and spatial ability, environmental and social awareness, analytical and logical reasoning, language and creativity, and design thinking. Two-part exam — Part A (computer-based) and Part B (drawing, only shortlisted).",
    eligibility: "Class 12 pass in any stream. Maximum 2 attempts in consecutive years. Age: born on or after Oct 1, 2001.",
    applicationStart: "Oct 2025",
    applicationEnd: "Nov 2025",
    examDate: "Jan 2026",
    resultDate: "Mar 2026",
    totalSeats: 220,
    candidatesAppearing: "~20,000",
    mode: "both" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["iit", "cfti"],
    acceptedBy: ["IIT Bombay B.Des", "IIT Delhi B.Des", "IIT Hyderabad B.Des", "IIT Guwahati B.Des", "IISc UG Research"],
  },
  {
    id: "nid-dat",
    name: "NID Design Aptitude Test",
    shortName: "NID DAT",
    category: "design" as const,
    level: "ug" as const,
    conductingBody: "National Institute of Design Ahmedabad",
    conductingBodyUrl: "https://www.nid.edu",
    officialWebsite: "https://admissions.nid.edu",
    description: "Entrance for all 19 NID campuses for B.Des and M.Des programmes. Tests design aptitude, observation, and creative problem-solving skills through drawing and studio exercises. Prelims (online) + Mains (studio test) format.",
    eligibility: "B.Des: Class 12 pass in any stream. M.Des: Bachelor's degree in any discipline. No minimum percentage.",
    applicationStart: "Oct 2025",
    applicationEnd: "Nov 2025",
    examDate: "Jan 2026 (Prelims) / Feb 2026 (Mains)",
    resultDate: "Apr 2026",
    totalSeats: 1400,
    candidatesAppearing: "~40,000",
    mode: "both" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["cfti"],
    acceptedBy: ["All 19 National Institute of Design campuses"],
  },
  {
    id: "nift-entrance",
    name: "NIFT Entrance Examination",
    shortName: "NIFT Entrance",
    category: "design" as const,
    level: "ug" as const,
    conductingBody: "National Institute of Fashion Technology",
    conductingBodyUrl: "https://nift.ac.in",
    officialWebsite: "https://nifttest.nta.nic.in",
    description: "Admission to all 17 NIFT campuses for B.Des, B.FTech, M.Des, MFM, and MFTech programmes. Creative Ability Test (CAT) + General Ability Test (GAT) format. Tests fashion design sense, colour, texture, and creative visualisation.",
    eligibility: "UG: Class 12 pass. PG: Bachelor's degree in relevant field. Maximum age 25 years for UG.",
    applicationStart: "Nov 2025",
    applicationEnd: "Jan 2026",
    examDate: "Feb 2026",
    resultDate: "May 2026",
    totalSeats: 4080,
    candidatesAppearing: "~1 lakh",
    mode: "both" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["cfti"],
    acceptedBy: ["All 17 NIFT campuses across India"],
  },
  {
    id: "ceed",
    name: "Common Entrance Examination for Design",
    shortName: "CEED",
    category: "design" as const,
    level: "pg" as const,
    conductingBody: "IIT Bombay",
    conductingBodyUrl: "https://www.iitb.ac.in",
    officialWebsite: "https://ceed.iitb.ac.in",
    description: "Entrance for M.Des programmes at IITs and IISc. Tests design skills, visual communication, and analytical thinking. Qualifying CEED also makes candidates eligible for design-related PhD programmes at IITs.",
    eligibility: "Bachelor's degree in any discipline (10+2+4 or 10+2+3+1). Final year students eligible.",
    applicationStart: "Oct 2025",
    applicationEnd: "Nov 2025",
    examDate: "Jan 2026",
    resultDate: "Mar 2026",
    totalSeats: 200,
    candidatesAppearing: "~15,000",
    mode: "both" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["iit", "cfti"],
    acceptedBy: ["IIT Bombay M.Des", "IIT Delhi M.Des", "IIT Guwahati M.Des", "IISc M.Des", "IIT Hyderabad M.Des"],
  },

  // ── SCIENCES ─────────────────────────────────────────────────
  {
    id: "iiser-iat",
    name: "IISER Aptitude Test",
    shortName: "IISER IAT",
    category: "sciences" as const,
    level: "ug" as const,
    conductingBody: "Joint Implementation Committee — IISERs",
    conductingBodyUrl: "https://www.iiseradmission.in",
    officialWebsite: "https://www.iiseradmission.in",
    description: "Entrance for 5-year BS-MS dual degree at all 7 IISERs. Tests Biology, Chemistry, Mathematics, and Physics at JEE Advanced level. Fully government-funded scholarships (INSPIRE fellowship) for all admitted students.",
    eligibility: "Class 12 with 60% in PCM/PCB (55% for SC/ST). JEE Advanced/KVPY qualifier can apply directly without IAT.",
    applicationStart: "Apr 2026",
    applicationEnd: "May 2026",
    examDate: "Jun 2026",
    resultDate: "Jun 2026",
    totalSeats: 2040,
    candidatesAppearing: "~30,000",
    mode: "online" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["cfti"],
    acceptedBy: ["All 7 IISERs — Pune, Kolkata, Mohali, Bhopal, TVM, Tirupati, Berhampur"],
  },
  {
    id: "cuet-ug",
    name: "Common University Entrance Test Undergraduate",
    shortName: "CUET UG",
    category: "sciences" as const,
    level: "ug" as const,
    conductingBody: "National Testing Agency (NTA)",
    conductingBodyUrl: "https://nta.ac.in",
    officialWebsite: "https://cuet.samarth.ac.in",
    description: "Common entrance replacing separate university exams for admissions to all 46 Central Universities including Delhi University, JNU, BHU, AMU, and Hyderabad University. Tests domain knowledge in chosen subjects plus language and general aptitude. Mandatory since 2022.",
    eligibility: "Class 12 pass (or appearing) in any stream. No minimum percentage requirement at national level.",
    applicationStart: "Feb 2026",
    applicationEnd: "Mar 2026",
    examDate: "May–Jun 2026",
    resultDate: "Jul 2026",
    totalSeats: 300000,
    candidatesAppearing: "~14 lakh",
    mode: "online" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["central-university", "state-university"],
    acceptedBy: ["All 46 Central Universities", "Delhi University", "JNU", "BHU", "AMU", "250+ participating universities"],
  },
  {
    id: "ugc-net",
    name: "UGC National Eligibility Test",
    shortName: "UGC NET",
    category: "sciences" as const,
    level: "pg" as const,
    conductingBody: "National Testing Agency (NTA)",
    conductingBodyUrl: "https://nta.ac.in",
    officialWebsite: "https://ugcnet.nta.ac.in",
    description: "Determines eligibility for Assistant Professor and Junior Research Fellowship (JRF) in Indian universities and colleges. Conducted twice a year in 83+ subjects. JRF awardees receive Rs 37,000/month fellowship for PhD research.",
    eligibility: "Master's degree with minimum 55% marks (50% for OBC/SC/ST/PWD). No upper age limit for AP. Max 30 years for JRF (35 for reserved).",
    applicationStart: "Nov 2025 / Apr 2026",
    applicationEnd: "Dec 2025 / May 2026",
    examDate: "Jun 2026 / Dec 2026",
    resultDate: "Aug 2026 / Jan 2027",
    totalSeats: null,
    candidatesAppearing: "~10–12 lakh per cycle",
    mode: "online" as const,
    frequency: "biannual" as const,
    eligibleInstitutionTypes: ["central-university", "state-university", "cfti"],
    acceptedBy: ["All UGC-recognised universities and colleges for teaching/research positions"],
  },

  // ── CIVIL SERVICES ───────────────────────────────────────────
  {
    id: "upsc-cse",
    name: "UPSC Civil Services Examination",
    shortName: "UPSC CSE",
    category: "civil-services" as const,
    level: "pg" as const,
    conductingBody: "Union Public Service Commission (UPSC)",
    conductingBodyUrl: "https://www.upsc.gov.in",
    officialWebsite: "https://www.upsc.gov.in",
    description: "India's most prestigious examination selecting IAS, IPS, IFS, and 24 other Group-A Central Services officers. Three stages: Prelims (June), Mains (September), and Personality Test/Interview (March). Approximately 1,000 officers selected annually.",
    eligibility: "Any bachelor's degree from a recognised university. Age 21–32 years (27 for OBC, 37 for SC/ST). Max 6 attempts (9 for OBC, unlimited for SC/ST).",
    applicationStart: "Feb 2026",
    applicationEnd: "Mar 2026",
    examDate: "Jun 2026 (Prelims) / Sep 2026 (Mains)",
    resultDate: "Apr 2027 (Final)",
    totalSeats: 1056,
    candidatesAppearing: "~10–11 lakh",
    mode: "offline" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["iit", "nit", "iim", "central-university", "state-university"],
    acceptedBy: ["IAS, IPS, IFS, IRTS, IDAS, IPS and 24 other central services"],
  },
  {
    id: "upsc-nda",
    name: "NDA & NA Examination",
    shortName: "NDA / NA",
    category: "civil-services" as const,
    level: "ug" as const,
    conductingBody: "Union Public Service Commission (UPSC)",
    conductingBodyUrl: "https://www.upsc.gov.in",
    officialWebsite: "https://www.upsc.gov.in",
    description: "Entrance to National Defence Academy (Army, Navy, Air Force wings) and Naval Academy (10+2 Cadet Entry). Conducted twice a year. Tests Mathematics and General Ability. SSB interview is the second stage.",
    eligibility: "Class 12 (PCM for Air Force/Navy; any stream for Army). Age 16.5–19.5 years. Unmarried male/female (female admitted from 2021).",
    applicationStart: "Dec 2025 / May 2026",
    applicationEnd: "Jan 2026 / Jun 2026",
    examDate: "Apr & Sep 2026",
    resultDate: "Jun & Nov 2026",
    totalSeats: 400,
    candidatesAppearing: "~5 lakh per cycle",
    mode: "offline" as const,
    frequency: "biannual" as const,
    eligibleInstitutionTypes: ["cfti"],
    acceptedBy: ["National Defence Academy (Pune)", "Naval Academy (Ezhimala)"],
  },
  {
    id: "ssc-cgl",
    name: "Staff Selection Commission Combined Graduate Level",
    shortName: "SSC CGL",
    category: "civil-services" as const,
    level: "pg" as const,
    conductingBody: "Staff Selection Commission (SSC)",
    conductingBodyUrl: "https://ssc.nic.in",
    officialWebsite: "https://ssc.nic.in",
    description: "Recruitment to Group B and C posts in various central government ministries, departments, and organisations. Includes Income Tax Inspector, CBI Sub-Inspector, Audit Officer, and Statistical Investigator posts. 4-tier selection process.",
    eligibility: "Bachelor's degree in any discipline. Age 18–27 years (varies by post). Relaxation for reserved categories.",
    applicationStart: "Jul 2025",
    applicationEnd: "Aug 2025",
    examDate: "Sep–Nov 2025 (Tier 1) / Jan 2026 (Tier 2)",
    resultDate: "Apr 2026 (Final)",
    totalSeats: 17727,
    candidatesAppearing: "~30–35 lakh",
    mode: "online" as const,
    frequency: "annual" as const,
    eligibleInstitutionTypes: ["central-university", "state-university", "iit", "nit"],
    acceptedBy: ["All central government Group B & C posts across 50+ ministries"],
  },

  // ── ARCHITECTURE / PLANNING ──────────────────────────────────
  {
    id: "nata",
    name: "National Aptitude Test in Architecture",
    shortName: "NATA",
    category: "design" as const,
    level: "ug" as const,
    conductingBody: "Council of Architecture (COA)",
    conductingBodyUrl: "https://www.coa.gov.in",
    officialWebsite: "https://nata.in",
    description: "Mandatory for admission to B.Arch programmes at all 480+ COA-recognised architecture schools including SPAs, NITs, and IITs offering B.Arch. Tests drawing, observation, critical thinking, and aesthetic sense. Two attempts per year.",
    eligibility: "Class 12 with PCM and minimum 50% in aggregate. No age limit.",
    applicationStart: "Jan 2026",
    applicationEnd: "Feb 2026",
    examDate: "Apr & Jun 2026",
    resultDate: "May & Jul 2026",
    totalSeats: 45000,
    candidatesAppearing: "~75,000",
    mode: "both" as const,
    frequency: "biannual" as const,
    eligibleInstitutionTypes: ["nit", "iit", "cfti", "central-university", "state-university"],
    acceptedBy: ["All 3 SPAs", "NITs offering B.Arch (Calicut, Rourkela, Patna, Bhopal)", "IIT Kharagpur B.Arch", "480+ architecture colleges"],
  },
];

router.get("/exams", (_req, res): void => {
  res.json(ListExamsResponse.parse(exams));
});

export default router;
