import { Router, type IRouter } from "express";
import { GetStateStatsResponse } from "@workspace/api-zod";

const router: IRouter = Router();

// Data: UDISE+ 2022-23, NFHS-5, Census 2011 projections
// geoName must match the NAME_1 field in the india-states.json GeoJSON

router.get("/stats/states", async (_req, res): Promise<void> => {
  const states = [
    {
      state: "Andaman & Nicobar Islands",
      geoName: "Andaman and Nicobar",
      region: "east" as const,
      dropoutRate: 3.2,
      primaryGer: 98.5,
      secondaryGer: 90.2,
      literacyRate: 86.3,
      outOfSchoolChildren: 850,
      girlsDropoutRate: 2.8,
      highlight: "Highest secondary GER among island union territories.",
    },
    {
      state: "Andhra Pradesh",
      geoName: "Andhra Pradesh",
      region: "south" as const,
      dropoutRate: 14.7,
      primaryGer: 98.2,
      secondaryGer: 74.3,
      literacyRate: 67.4,
      outOfSchoolChildren: 320000,
      girlsDropoutRate: 16.8,
      highlight: "AP Residential Schools (Gurukuls) serve 3.5 lakh ST/SC students annually.",
    },
    {
      state: "Arunachal Pradesh",
      geoName: "Arunachal Pradesh",
      region: "northeast" as const,
      dropoutRate: 21.3,
      primaryGer: 89.4,
      secondaryGer: 62.1,
      literacyRate: 66.9,
      outOfSchoolChildren: 45000,
      girlsDropoutRate: 23.1,
      highlight: "Highest tribal OOSC rate in NE; remote terrain limits school access.",
    },
    {
      state: "Assam",
      geoName: "Assam",
      region: "northeast" as const,
      dropoutRate: 16.2,
      primaryGer: 95.3,
      secondaryGer: 64.4,
      literacyRate: 73.2,
      outOfSchoolChildren: 380000,
      girlsDropoutRate: 18.4,
      highlight: "Mid-day meal coverage improved to 97% of schools in 2022-23.",
    },
    {
      state: "Bihar",
      geoName: "Bihar",
      region: "east" as const,
      dropoutRate: 19.7,
      primaryGer: 96.1,
      secondaryGer: 40.7,
      literacyRate: 63.8,
      outOfSchoolChildren: 2100000,
      girlsDropoutRate: 21.6,
      highlight: "Highest absolute OOSC count. Bihar's conditional girls' scholarship reaches 1.2 million beneficiaries.",
    },
    {
      state: "Chandigarh",
      geoName: "Chandigarh",
      region: "north" as const,
      dropoutRate: 2.1,
      primaryGer: 102.3,
      secondaryGer: 97.4,
      literacyRate: 86.4,
      outOfSchoolChildren: 1200,
      girlsDropoutRate: 1.8,
      highlight: "Best-performing UT — near-universal enrollment and highest secondary GER.",
    },
    {
      state: "Chhattisgarh",
      geoName: "Chhattisgarh",
      region: "central" as const,
      dropoutRate: 17.1,
      primaryGer: 97.2,
      secondaryGer: 56.8,
      literacyRate: 70.3,
      outOfSchoolChildren: 290000,
      girlsDropoutRate: 19.4,
      highlight: "Bastar's ST communities served by 12 Eklavya Model Residential Schools.",
    },
    {
      state: "Delhi",
      geoName: "Delhi",
      region: "north" as const,
      dropoutRate: 4.2,
      primaryGer: 103.4,
      secondaryGer: 94.5,
      literacyRate: 86.3,
      outOfSchoolChildren: 67000,
      girlsDropoutRate: 4.0,
      highlight: "Delhi govt school Board results improved 23% since 2015 overhaul.",
    },
    {
      state: "Goa",
      geoName: "Goa",
      region: "west" as const,
      dropoutRate: 3.4,
      primaryGer: 105.2,
      secondaryGer: 89.3,
      literacyRate: 88.7,
      outOfSchoolChildren: 4200,
      girlsDropoutRate: 3.1,
      highlight: "Highest state literacy rate (88.7%) and one of the lowest dropout rates.",
    },
    {
      state: "Gujarat",
      geoName: "Gujarat",
      region: "west" as const,
      dropoutRate: 10.5,
      primaryGer: 98.7,
      secondaryGer: 65.4,
      literacyRate: 78.0,
      outOfSchoolChildren: 380000,
      girlsDropoutRate: 12.4,
      highlight: "Vanbandhu Kalyan Yojana provides residential schooling for tribal children.",
    },
    {
      state: "Haryana",
      geoName: "Haryana",
      region: "north" as const,
      dropoutRate: 8.3,
      primaryGer: 101.2,
      secondaryGer: 74.8,
      literacyRate: 75.6,
      outOfSchoolChildren: 180000,
      girlsDropoutRate: 10.1,
      highlight: "Beti Bachao Beti Padhao origin state; girls' enrollment rose 18% in 10 years.",
    },
    {
      state: "Himachal Pradesh",
      geoName: "Himachal Pradesh",
      region: "north" as const,
      dropoutRate: 5.6,
      primaryGer: 100.7,
      secondaryGer: 86.3,
      literacyRate: 82.8,
      outOfSchoolChildren: 22000,
      girlsDropoutRate: 5.2,
      highlight: "2nd highest secondary GER among general states; strong mid-day meal compliance.",
    },
    {
      state: "Jammu & Kashmir",
      geoName: "Jammu and Kashmir",
      region: "north" as const,
      dropoutRate: 9.1,
      primaryGer: 99.2,
      secondaryGer: 73.4,
      literacyRate: 67.2,
      outOfSchoolChildren: 95000,
      girlsDropoutRate: 10.3,
      highlight: "Post-2019 expansion of Sanik Schools and Eklavya Residential Schools.",
    },
    {
      state: "Jharkhand",
      geoName: "Jharkhand",
      region: "east" as const,
      dropoutRate: 18.3,
      primaryGer: 95.4,
      secondaryGer: 52.2,
      literacyRate: 66.4,
      outOfSchoolChildren: 390000,
      girlsDropoutRate: 21.7,
      highlight: "Highest ST proportion (26%); Kasturba Gandhi Balika Vidyalayas expanding in tribal blocks.",
    },
    {
      state: "Karnataka",
      geoName: "Karnataka",
      region: "south" as const,
      dropoutRate: 9.7,
      primaryGer: 99.3,
      secondaryGer: 71.2,
      literacyRate: 75.6,
      outOfSchoolChildren: 390000,
      girlsDropoutRate: 11.3,
      highlight: "Rajiv Gandhi Scholarship for SC/ST students well-implemented in all 30 districts.",
    },
    {
      state: "Kerala",
      geoName: "Kerala",
      region: "south" as const,
      dropoutRate: 4.3,
      primaryGer: 101.2,
      secondaryGer: 98.5,
      literacyRate: 96.2,
      outOfSchoolChildren: 18000,
      girlsDropoutRate: 3.9,
      highlight: "Highest literacy (96.2%) and secondary GER in India. National benchmark for equity.",
    },
    {
      state: "Lakshadweep",
      geoName: "Lakshadweep",
      region: "south" as const,
      dropoutRate: 2.4,
      primaryGer: 99.7,
      secondaryGer: 94.2,
      literacyRate: 91.8,
      outOfSchoolChildren: 310,
      girlsDropoutRate: 2.1,
      highlight: "Near-universal literacy (91.8%); smallest OOSC count of any UT.",
    },
    {
      state: "Madhya Pradesh",
      geoName: "Madhya Pradesh",
      region: "central" as const,
      dropoutRate: 16.2,
      primaryGer: 96.8,
      secondaryGer: 54.6,
      literacyRate: 69.3,
      outOfSchoolChildren: 1200000,
      girlsDropoutRate: 18.9,
      highlight: "Ladli Laxmi scheme improves girls' enrollment; still 12 lakh OOSC remain.",
    },
    {
      state: "Maharashtra",
      geoName: "Maharashtra",
      region: "west" as const,
      dropoutRate: 9.2,
      primaryGer: 100.1,
      secondaryGer: 75.3,
      literacyRate: 82.9,
      outOfSchoolChildren: 820000,
      girlsDropoutRate: 10.8,
      highlight: "Akanksha Foundation reaches 15,000+ slum children in Mumbai and Pune.",
    },
    {
      state: "Manipur",
      geoName: "Manipur",
      region: "northeast" as const,
      dropoutRate: 12.4,
      primaryGer: 96.8,
      secondaryGer: 68.4,
      literacyRate: 76.9,
      outOfSchoolChildren: 52000,
      girlsDropoutRate: 14.2,
      highlight: "Conflict in hill districts disrupts school attendance; KGBV hostels improving retention.",
    },
    {
      state: "Meghalaya",
      geoName: "Meghalaya",
      region: "northeast" as const,
      dropoutRate: 22.1,
      primaryGer: 94.3,
      secondaryGer: 57.2,
      literacyRate: 74.4,
      outOfSchoolChildren: 48000,
      girlsDropoutRate: 24.3,
      highlight: "Highest dropout in NE India; English-medium barrier affects tribal communities.",
    },
    {
      state: "Mizoram",
      geoName: "Mizoram",
      region: "northeast" as const,
      dropoutRate: 7.3,
      primaryGer: 99.1,
      secondaryGer: 82.3,
      literacyRate: 91.3,
      outOfSchoolChildren: 8500,
      girlsDropoutRate: 7.6,
      highlight: "2nd highest literacy in NE; strong church-run school tradition boosts enrollment.",
    },
    {
      state: "Nagaland",
      geoName: "Nagaland",
      region: "northeast" as const,
      dropoutRate: 11.8,
      primaryGer: 97.2,
      secondaryGer: 67.4,
      literacyRate: 79.6,
      outOfSchoolChildren: 28000,
      girlsDropoutRate: 12.9,
      highlight: "Remote terrain and conflict affect completion; government residential schools expanding.",
    },
    {
      state: "Odisha",
      geoName: "Orissa",
      region: "east" as const,
      dropoutRate: 15.8,
      primaryGer: 96.5,
      secondaryGer: 59.4,
      literacyRate: 72.9,
      outOfSchoolChildren: 620000,
      girlsDropoutRate: 18.2,
      highlight: "Mo School programme leverages community alumni to improve school quality.",
    },
    {
      state: "Puducherry",
      geoName: "Puducherry",
      region: "south" as const,
      dropoutRate: 3.7,
      primaryGer: 104.2,
      secondaryGer: 92.3,
      literacyRate: 85.8,
      outOfSchoolChildren: 3800,
      girlsDropoutRate: 3.4,
      highlight: "Strong central-government school network; high retention and literacy.",
    },
    {
      state: "Punjab",
      geoName: "Punjab",
      region: "north" as const,
      dropoutRate: 6.4,
      primaryGer: 100.4,
      secondaryGer: 82.3,
      literacyRate: 75.8,
      outOfSchoolChildren: 98000,
      girlsDropoutRate: 7.1,
      highlight: "Schools of Eminence model showing strong improvements in government school quality.",
    },
    {
      state: "Rajasthan",
      geoName: "Rajasthan",
      region: "north" as const,
      dropoutRate: 15.9,
      primaryGer: 97.1,
      secondaryGer: 56.3,
      literacyRate: 66.1,
      outOfSchoolChildren: 1600000,
      girlsDropoutRate: 20.3,
      highlight: "High girls' dropout from early marriage; Gargi Puraskar scheme active across all districts.",
    },
    {
      state: "Sikkim",
      geoName: "Sikkim",
      region: "northeast" as const,
      dropoutRate: 4.1,
      primaryGer: 98.6,
      secondaryGer: 88.4,
      literacyRate: 81.4,
      outOfSchoolChildren: 3200,
      girlsDropoutRate: 4.4,
      highlight: "Best-performing hill state; strong teacher training and small class sizes.",
    },
    {
      state: "Tamil Nadu",
      geoName: "Tamil Nadu",
      region: "south" as const,
      dropoutRate: 7.8,
      primaryGer: 100.3,
      secondaryGer: 84.2,
      literacyRate: 80.1,
      outOfSchoolChildren: 310000,
      girlsDropoutRate: 8.4,
      highlight: "Mid-day meal programme originated in TN (1925); near-universal primary enrollment.",
    },
    {
      state: "Tripura",
      geoName: "Tripura",
      region: "northeast" as const,
      dropoutRate: 10.7,
      primaryGer: 98.9,
      secondaryGer: 71.4,
      literacyRate: 87.7,
      outOfSchoolChildren: 32000,
      girlsDropoutRate: 12.1,
      highlight: "Highest literacy in NE (87.7%); rapid improvement since 2018 under new education policy.",
    },
    {
      state: "Uttar Pradesh",
      geoName: "Uttar Pradesh",
      region: "north" as const,
      dropoutRate: 16.4,
      primaryGer: 97.2,
      secondaryGer: 52.3,
      literacyRate: 67.7,
      outOfSchoolChildren: 4200000,
      girlsDropoutRate: 19.1,
      highlight: "Largest OOSC count (42 lakh). NIPUN Bharat mission targets foundational literacy in 75 districts.",
    },
    {
      state: "Uttarakhand",
      geoName: "Uttaranchal",
      region: "north" as const,
      dropoutRate: 8.9,
      primaryGer: 100.2,
      secondaryGer: 72.4,
      literacyRate: 78.8,
      outOfSchoolChildren: 73000,
      girlsDropoutRate: 10.2,
      highlight: "Mountain geography creates access barriers; e-Vidyaloka connects 200+ hill schools digitally.",
    },
    {
      state: "West Bengal",
      geoName: "West Bengal",
      region: "east" as const,
      dropoutRate: 11.3,
      primaryGer: 99.4,
      secondaryGer: 67.3,
      literacyRate: 77.0,
      outOfSchoolChildren: 760000,
      girlsDropoutRate: 13.4,
      highlight: "Kanyashree Prakalpa conditional cash transfer won UN Public Service Award in 2017.",
    },
  ];

  res.json(GetStateStatsResponse.parse(states));
});

export default router;
